language: python
python:
    - "2.7"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
    - python setup.py install
    - nosetests --with-coverage --cover-package cloudshell/networking

after_success:
    - coveralls